### ISSUE TITLE
The performance of the binary classification system

### ISSUE THREAD

**Issue by vhientran** [Saintfe/RECENT#1]
Hi @Saintfe ,

Thank you for releasing your source code. In the experimental setup (section 3.2), you mentioned that a binary classifier is first learned to distinguish between 41 semantic relations and _no_relation_. Could you please give me the performance of this first step? For example, [F1-score](https://github.com/Saintfe/RECENT/blob/6e91dcdbfa90bf3aa94dc9f675da74dfda6d5669/SpanBERT/code/run_tacred_binary.py#L248) of the binary classifier. Thanks so much for your help!

**Comment by Saintfe** [comment]
The F1-score of `RECENT_GCN`  is 69.869%.
The F1-score of `RECENT_SpanBERT`  is 72.363%.

**Comment by vhientran** [comment]
I got it. Thank you for your quick reply!
